title: "Remote IT Help"
email: "hello@it-help.tech"
description: "Expert Remote IT Support - DMARC, DNS, macOS, & Email Deliverability"
logo: /assets/images/logo-blue.png
baseurl: ""
url: "https://remote-it-help.com"

theme: jekyll-theme-minimal
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

permalink: /:name.html

exclude:
  - README.md
  - test.md

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap # Added for XML sitemap generation

feed:
  path: /feed.xml
