name: Deploy Jekyll → S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET: remote-it-help.com
      DIST_ID: ${{ secrets.CF_DIST_ID }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Ruby for Jekyll (use Ruby 3.1.0 or above)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Updated Ruby version for compatibility with Bundler

      # Install Jekyll and Bundler
      - name: Install Jekyll and Bundler
        run: |
          gem install bundler
          bundle install

      # Build the Jekyll site
      - name: Build the Jekyll site
        run: |
          bundle exec jekyll build

      # Sync the built site to S3
      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ env.BUCKET }}
          AWS_REGION: us-east-1  # Update this with your AWS region
          SOURCE_DIR: ./_site
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id $DIST_ID --paths '/*'
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
