name: Deploy Astro → S3 + CloudFront
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET: remote-it-help.com
      DIST_ID: ${{ secrets.CF_DIST_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 8 }
      - run: pnpm install
      - run: pnpm run build

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with: { args: --delete }
        env:
          AWS_S3_BUCKET: ${{ env.BUCKET }}
          AWS_REGION: us-east-1
          SOURCE_DIR: dist
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id $DIST_ID --paths '/*'
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
